### ISSUE TITLE
in.nextLong() seems incorrect

### ISSUE THREAD

**Issue by abhinav272** [lyubomyr-shaydariv/ext-gson#1]
https://github.com/lyubomyr-shaydariv/ext-gson/blob/ec8eda54e2682b4575a58259b7203d9f12d9f3e4/src/main/java/lsh/ext/gson/adapters/EpochDateTypeAdapter.java#L40

While using in.nextLong() it is using epoch but when passing epoch in Date constructor incorrect year is returned as it expects milliseconds in UNIX.

so in read() method if we do in.nextLong()*1000 and in write() method we do value.getTime()/1000,
Then it works fine.

What say?

**Comment by lyubomyr-shaydariv** [comment]
@abhinav272 Yes, you're totally right. Fixed in feaf47e9e82c821513efe331622c0146207f43a8.
